/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Playlist = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'trackIds' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const OfflineTrack = IDL.Record({
  'id' : IDL.Text,
  'albumArt' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'audioUrl' : IDL.Text,
  'genre' : IDL.Text,
  'artist' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRecentlyPlayed' : IDL.Func([IDL.Text], [], []),
  'addTrackToPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPlaylist' : IDL.Func([IDL.Text], [Playlist], []),
  'deletePlaylist' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLikedTracks' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMyPlaylists' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
  'getOfflineTracks' : IDL.Func([], [IDL.Vec(OfflineTrack)], ['query']),
  'getPlaylist' : IDL.Func([IDL.Text], [Playlist], ['query']),
  'getRecentlyPlayed' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeTrack' : IDL.Func([IDL.Text], [], []),
  'removeOfflineTrack' : IDL.Func([IDL.Text], [], []),
  'removeTrackFromPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveOfflineTrack' : IDL.Func([OfflineTrack], [], []),
  'unlikeTrack' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Playlist = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'trackIds' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const OfflineTrack = IDL.Record({
    'id' : IDL.Text,
    'albumArt' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'audioUrl' : IDL.Text,
    'genre' : IDL.Text,
    'artist' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRecentlyPlayed' : IDL.Func([IDL.Text], [], []),
    'addTrackToPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPlaylist' : IDL.Func([IDL.Text], [Playlist], []),
    'deletePlaylist' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLikedTracks' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMyPlaylists' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
    'getOfflineTracks' : IDL.Func([], [IDL.Vec(OfflineTrack)], ['query']),
    'getPlaylist' : IDL.Func([IDL.Text], [Playlist], ['query']),
    'getRecentlyPlayed' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeTrack' : IDL.Func([IDL.Text], [], []),
    'removeOfflineTrack' : IDL.Func([IDL.Text], [], []),
    'removeTrackFromPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveOfflineTrack' : IDL.Func([OfflineTrack], [], []),
    'unlikeTrack' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };